"""Centralized user-facing CLI strings used by cli.main."""

APP_NAME = "contextcore"
APP_HELP = "ContextCore — unified local search for Claude and other AI tools."

HELP_PORT_LISTENING = "Port the server is listening on."
HELP_PORT_BIND = "Port to bind the server to."
HELP_ENABLE_RELOAD = "Enable hot-reload for development."
HELP_INDEX_TARGET = "Optional directory to index. Omit to scan all configured directories."
HELP_ADD_FOLDER_PATH = "Directory to add to the watch list."
HELP_ADD_FOLDER_NO_INDEX = "Add the folder without indexing it immediately."
HELP_INSTALL_MODEL = "Which model to download: [bold]clip[/bold], [bold]audio[/bold], or [bold]all[/bold]."
HELP_REGISTER_TOOL = "Tool to register with. Options: claude-desktop, claude-code, cline, cursor."
HELP_REPORT_MESSAGE = "Issue description. Example: contextcore report image search returns empty results"
HELP_REPORT_REPO = "Optional GitHub repo override (owner/repo). Default: detected from git origin."
HELP_REPORT_TITLE = "Optional issue title override."
HELP_UPDATE_RESTART = "Restart ContextCore background server after pulling updates."
HELP_SERVER_ACTION = "Action to run: start, stop, restart, status."
HELP_UNINSTALL_YES = "Skip confirmation prompt."
HELP_UNINSTALL_DRY_RUN = "Show what would be removed."
HELP_UNINSTALL_REMOVE_PACKAGE = "Also run pip uninstall for contextcore after cleanup."
HELP_UNINSTALL_PURGE_MODEL_CACHE = "Also remove local Hugging Face/Torch model cache folders."

HELP_BENCHMARK_DATASET = "BEIR dataset name (default: scifact)."
HELP_BENCHMARK_TOP_K = "Top-k documents to retrieve per query."
HELP_BENCHMARK_MAX_QUERIES = "Optional limit for quick iterations (0 = all)."
HELP_BENCHMARK_DATASETS_DIR = "Directory for BEIR datasets cache."
HELP_BENCHMARK_OUTPUT_JSON = "Optional path to save run + summary JSON."
HELP_BENCHMARK_MEASURE_TOKENS = "Compute token usage reduction with tiktoken."
HELP_BENCHMARK_TOKEN_ENCODING = "tiktoken encoding name."
HELP_BENCHMARK_CONTEXT_TOP_K = "Top-k retrieved chunks to count for ContextCore tokens (0 uses --top-k)."
HELP_BENCHMARK_SYSTEMS = (
    "Comma-separated retrieval systems to evaluate. "
    "Supported: contextcore_hybrid,bm25_only,trigram_only"
)
HELP_BENCHMARK_REPORT_CSV = "Optional CSV path for system comparison table."
HELP_BENCHMARK_REPORT_MD = "Optional Markdown path for system comparison table."

DEFAULT_BENCHMARK_DATASET = "scifact"
DEFAULT_BENCHMARK_TOKEN_ENCODING = "cl100k_base"
DEFAULT_BENCHMARK_SYSTEMS = "contextcore_hybrid,bm25_only,trigram_only"
